before_script:
    - date
    - uname -a
    - printenv | sort

gcc:
    image: gpdowning/gcc
    script:
    - cat Makefile
    - make versions
    - ls -al
    - make test
    - ls -al
    - make check
    - ls -al
